
services:
  auth-service:
    build: ./authservice
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: "mongodb+srv://CTSE:CTSE@ctse.kewjrct.mongodb.net/ctse?retryWrites=true&w=majority&appName=CTSE"
      JWT_SECRET: "shashin99"
    networks:
      - app-network

  user-service:
    build: ./userservice
    ports:
      - "5002:5002"
    environment:
      MONGO_URI: "mongodb+srv://CTSE:CTSE@ctse.kewjrct.mongodb.net/ctse?retryWrites=true&w=majority&appName=CTSE"
      JWT_SECRET: "shashin99"
    networks:
      - app-network

  api-gateway:
    build: ./APIGateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - user-service
    environment:
      - PORT=5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
