version: "3"

services:
    mongo:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db

        environment:
            MONGO_INITDB_ROOT_USERNAME: CTSE
            MONGO_INITDB_ROOT_PASSWORD: CTSE

    user-service:
        build: .
        ports:
            - "5001:5001"
        depends_on:
            - mongo
        environment:
            MONGO_URI: "mongodb+srv://CTSE:CTSE@ctse.kewjrct.mongodb.net/ctse?retryWrites=true&w=majority&appName=CTSE"

volumes:
    mongo_data:
