name: CICD Pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-north-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              with:
                  mask-password: "true"
            - name: Build and Push AuthService
              id: auth
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  IMAGE_TAG: latest
                  REPOSITORY: ctse-auth
              run: |
                  docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG ./backend/authservice
                  docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
                  echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

        outputs:
            auth-image-uri: ${{ steps.auth.outputs.image }}

    deploy:
        name: Deploy to Amazon ECS
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-north-1
            - name: Update ECS Task Definition for Auth Service
              id: auth-task-def
              uses: aws-actions/amazon-ecs-render-task-definition@v1
              with:
                  task-definition: ./backend/tasks/ctse-auth-task-definition.json
                  container-name: ctse-auth
                  image: ${{ needs.build.outputs.auth-image-uri }}

            - name: Deploy Updated Auth Service to ECS
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                  task-definition: ${{ steps.auth-task-def.outputs.task-definition }}
                  service: auth-service
                  cluster: ctseCluster
                  wait-for-service-stability: true
