name: CICD Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Debug - Show directory structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          ls -la ./userservice

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t shashin99/ctse-assignment:latest .
        working-directory: ./userservice

      - name: Push Docker Image to Docker Hub
        run: docker push shashin99/ctse-assignment:latest

  deploy:
    name: Deploy to Amazon ECS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Render Amazon ECS task definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          container-name: ctse-assignment-container
          image: shashin99/ctse-assignment:latest

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          service: userservice-app-serivce            
          cluster: devCluster            
          task-definition: ${{ steps.render-task.outputs.task-definition }}