name: CICD Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Debug - Show directory structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          ls -la ./userservice

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t shashin99/ctse-assignment .
        working-directory: ./userservice

      - name: Push Docker image to Docker Hub
        run: docker push shashin99/ctse-assignment:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull shashin99/ctse-assignment:latest

      - name: Stop and remove existing container (if exists)
        run: |
          if [ "$(docker ps -aq -f name=ctse-assignment-container)" ]; then
            docker rm -f ctse-assignment-container
          else
            echo "No existing container to remove"
          fi

      - name: Run new Docker container
        run: docker run -d -p 5001:5001 --name ctse-assignment-container shashin99/ctse-assignment:latest
